---

- name: Setup private docker registry
  hosts: localhost

  post_tasks:
    - name: Include NGINX role
      include_role:
        name: nginx
      when: registry_host is defined

  roles:
    - docker
    - docker-ce
    - registry

  become: True
